# Universal Windows Platform


trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/KGFramework.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/KGFramework.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\KGFramework.sln'
    vsVersion: '16.0'
    platform: 'x64'
    msbuildArchitecture: 'x64'
    createLogFile: true
    
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml
